export const tasks = [
  {
    id: 1,
    task: "Phasellus et sem eget",
    desc: "Lorem ipsum dolor sit amet consectetur",
    point: +500,
    image: "https://cdn.mallconomy.com/testcase/1.png",
  },
  {
    id: 2,
    task: "Proin in sem molestie",
    desc: "Vivamus sodales euismod ornare",
    point: +600,
    image: "https://cdn.mallconomy.com/testcase/2.png",
  },
  {
    id: 3,
    task: "Curabitur finibus lacus et justo",
    desc: "Class aptent taciti sociosqu ad litora",
    point: +850,
    image: "https://cdn.mallconomy.com/testcase/3.png",
  },
  {
    id: 4,
    task: "Aenean mattis elit non justo",
    desc: "Praesent eleifend lorem sit amet ipsum vulputate efficitur. Class aptent taciti!",
    point: +2560,
    image: "https://cdn.mallconomy.com/testcase/4.png",
  },
  {
    id: 5,
    task: "Vestibulum ante ipsum primis",
    desc: "Nulla faucibus egestas",
    point: +1100,
    image: "https://cdn.mallconomy.com/testcase/5.png",
  },
  {
    id: 6,
    task: "Curabitur a convallis",
    desc: "Morbi eget interdum sem",
    point: +10,
    image: "https://cdn.mallconomy.com/testcase/6.png",
  },
  {
    id: 7,
    task: "Aenean mattis elit non justo",
    desc: "Curabitur finibus lacus et justo tristique",
    point: +2560,
    image: "https://cdn.mallconomy.com/testcase/7.png",
  },
  {
    id: 8,
    task: "Aenean mattis elit non justo",
    desc: "Praesent eleifend lorem sit amet ipsum vulputate efficitur. Class aptent taciti!",
    point: +2560,
    image: "https://cdn.mallconomy.com/testcase/8.png",
  },
  {
    id: 9,
    task: "Proin in sem molestie",
    desc: "Vivamus sodales euismod ornare",
    point: +600,
    image: "https://cdn.mallconomy.com/testcase/9.png",
  },
  {
    id: 10,
    task: "Curabitur a convallis",
    desc: "Morbi eget interdum sem",
    point: +10,
    image: "https://cdn.mallconomy.com/testcase/10.png",
  },
];
